server:
  port: 19002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 192.168.111.168
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: woshiniba123
  rabbitmq:
    host: 192.168.111.168
    virtual-host: /lzm
    username: lzm
    password: lzm
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        concurrency:
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 100
        keep-alive: 60s
        max-size: 500
        queue-capacity: 1000
      shutdown:
        await-termination: true
        await-termination-period: 120
      thread-name-prefix: cart-task-


feign:
  sentinel:
    enabled: true


cart:
  jwt:
    pubKeyPath: C:\Users\10982\Desktop\work_space\gmall\rsa\pub.rsa
    cookieName: GMALL-TOKEN
    userKey: user-key
    expire: 15552000
