server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # \u5546\u54C1\u7BA1\u7406\u8DEF\u7531
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # \u8BA2\u5355\u7BA1\u7406\u8DEF\u7531
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # \u7528\u6237\u7BA1\u7406\u8DEF\u7531
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # \u4ED3\u5E93\u7BA1\u7406\u8DEF\u7531
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # \u8425\u9500\u7BA1\u7406\u8DEF\u7531
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: index-route1
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com, index.gmall.com, lzm.com
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route1
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: item-route2
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com,item.lzm.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com, register.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
gmall:
  gateway:
    jwt:
      cookieName: GMALL-TOKEN
      pubKeyPath: C:\Users\10982\Desktop\work_space\gmall\rsa\pub.rsa