server:
  port: 19001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

feign:
  sentinel:
    enabled: true

gmall:
  auth:
    jwt:
      pubKeyPath: C:\Users\10982\Desktop\work_space\gmall\rsa\pub.rsa
      priKeyPath: C:\Users\10982\Desktop\work_space\gmall\rsa\pri.rsa
      secret: lzm2390234@sef<<>>
      expire: 180
      cookieName: GMALL-TOKEN
      unick: unick

